spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/any?useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #¿ªÆôÍÕ·åÃüÃû×ª»»
server:
  port: 80